import numpy as np
arr=np.array([10,20,30])
print(arr)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.percentile(arr,25))
print(np.percentile(arr,50))
print(np.percentile(arr,75))
print(np.percentile(arr,100))
print(np.sum(arr))